Traceback (most recent call last):
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/codespace/.python/current/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

data = {'Patient': ['Patient 1']*11 + ['Patient 2']*11 + ['Patient 3']*11,
        'Date': ['2022-01-05','2022-01-05','2022-01-05', 
                 '2022-03-15','2022-03-15','2022-03-15',
                 '2022-05-30','2022-05-30','2022-05-30',  
                 '2022-08-12','2022-08-12','2022-08-12',
                 '2022-02-14','2022-02-14','2022-02-14',
                 '2022-04-20','2022-04-20','2022-04-20',
                 '2022-06-25','2022-06-25','2022-06-25',
                 '2022-09-05','2022-09-05','2022-09-05', 
                 '2022-03-02','2022-03-02','2022-03-02',
                 '2022-05-11','2022-05-11','2022-05-11',
                 '2022-07-19','2022-07-19','2022-07-19'],
        'Lab': ['A1C','Potassium','WBC']*11,
        'Value': [6.1,4.2,9.0,
                  5.8,4.0,8.5,
                  5.9,4.1,8.8,
                  6.0,4.3,9.5,
                  7.2,4.4,10.5,
                  7.0,4.5,10.0,
                  7.1,4.3,10.2,
                  6.9,4.4,9.8,
                  8.5,4.7,9.5,
                  8.3,4.6,9.0,
                  8.4,4.8,7.8]
       }

df = pl.DataFrame(data).with_columns(pl.col("Date").str.to_datetime(format="%Y-%m-%d").dt.date())
df
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 29[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      3[0m data [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mPatient[39m[38;5;124m'[39m: [[38;5;124m'[39m[38;5;124mPatient 1[39m[38;5;124m'[39m][38;5;241m*[39m[38;5;241m11[39m [38;5;241m+[39m [[38;5;124m'[39m[38;5;124mPatient 2[39m[38;5;124m'[39m][38;5;241m*[39m[38;5;241m11[39m [38;5;241m+[39m [[38;5;124m'[39m[38;5;124mPatient 3[39m[38;5;124m'[39m][38;5;241m*[39m[38;5;241m11[39m,
[1;32m      4[0m         [38;5;124m'[39m[38;5;124mDate[39m[38;5;124m'[39m: [[38;5;124m'[39m[38;5;124m2022-01-05[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124m2022-01-05[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124m2022-01-05[39m[38;5;124m'[39m, 
[1;32m      5[0m                  [38;5;124m'[39m[38;5;124m2022-03-15[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124m2022-03-15[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124m2022-03-15[39m[38;5;124m'[39m,
[0;32m   (...)[0m
[1;32m     26[0m                   [38;5;241m8.4[39m,[38;5;241m4.8[39m,[38;5;241m7.8[39m]
[1;32m     27[0m        }
[0;32m---> 29[0m df [38;5;241m=[39m [43mpl[49m[38;5;241m.[39mDataFrame(data)[38;5;241m.[39mwith_columns(pl[38;5;241m.[39mcol([38;5;124m"[39m[38;5;124mDate[39m[38;5;124m"[39m)[38;5;241m.[39mstr[38;5;241m.[39mto_datetime([38;5;28mformat[39m[38;5;241m=[39m[38;5;124m"[39m[38;5;124m%[39m[38;5;124mY-[39m[38;5;124m%[39m[38;5;124mm-[39m[38;5;132;01m%d[39;00m[38;5;124m"[39m)[38;5;241m.[39mdt[38;5;241m.[39mdate())
[1;32m     30[0m df

[0;31mNameError[0m: name 'pl' is not defined

